Agenda : Pandas 3

In [2]:
import pandas as pd

In [3]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [4]:
df = pd.read_csv(titanic_dataset_github_url)

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
df['Name'].str.len().head()

0    23
1    51
2    22
3    44
4    24
Name: Name, dtype: int64

In [13]:
'demoDog'.replace("d","D")

'DemoDog'

In [18]:
df['Name_replaced'] = df['Name'].str.replace("Mr", "Sir", regex=False).head()

In [19]:
df['Name_replaced'].head()

0                             Braund, Sir. Owen Harris
1    Cumings, Sirs. John Bradley (Florence Briggs T...
2                               Heikkinen, Miss. Laina
3        Futrelle, Sirs. Jacques Heath (Lily May Peel)
4                            Allen, Sir. William Henry
Name: Name_replaced, dtype: str

In [17]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [20]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [21]:
df.loc[1,'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [22]:
start = df.loc[1, 'Name'].find("(")

In [23]:
end = df.loc[1, 'Name'].find(")")

In [25]:
df.loc[1,'Name'][0:start] + df.loc[1,'Name'][end+1:]

'Cumings, Mrs. John Bradley '

In [30]:
def remove_substring(name):
    start = name.find("(")
    end = name.find(")")
    new_name = name[0:start] + name[end+1:]
    new_name = new_name.strip()
    return new_name

In [31]:
df['Name_trimmed'] = df['Name'].apply(remove_substring)

In [32]:
df['Name_trimmed'].head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_trimmed, dtype: str

In [34]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [ ]:
df.loc[1, 'Name_trimmed']

'Cumings, Mrs. John Bradley'

**Replace substrings with regex : regular expression**
```python
Regex allows you to replace patterns, not just fixed words.
Example:
Replace all numbers
Replace emails
Replace dates
Replace multiple spaces
Replace special characters

```python
Meaning of "\(.*\)"
\( → matches a literal opening parenthesis (
.* → matches any character (.) zero or more times (*)
\) → matches a literal closing parenthesis )

So this pattern matches:
Everything from the first ( to the last ) in the string.

In [40]:
df['Name'].str.replace(r"\(.*\)","Hello", regex=True).head()

0               Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley Hello
2                Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath Hello
4              Allen, Mr. William Henry
Name: Name, dtype: str

To validate an email address using regex in Python, here’s the correct and practical way to do it.

In [41]:
import re

pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"

email = "test.email123@gmail.com"

if re.match(pattern, email):
    print("Valid email")
else:
    print("Invalid email")

Valid email

```python
Explanation of the Regex
^                       → Start of string
[a-zA-Z0-9._%+-]+       → Username part (before @)
@                       → Must contain @
[a-zA-Z0-9.-]+          → Domain name
\.                      → Literal dot
[a-zA-Z]{2,}            → Extension (min 2 letters like com, org)
$                       → End of string

**Split and Access Elements**

In [42]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [43]:
df['Name'].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

In [44]:
df['Name'].str.split()[0]

['Braund,', 'Mr.', 'Owen', 'Harris']

In [49]:
df['Name'].str.split()[0][0]

'Braund,'

In [46]:
df['Name'].str.split().str[0].head()

0       Braund,
1      Cumings,
2    Heikkinen,
3     Futrelle,
4        Allen,
Name: Name, dtype: object

**strip spaces**

In [48]:
df['Name'].str.strip().head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

**find position of substring**

In [52]:
df['Name'].str.find("Mr").head() ##-1 means not available

0     8
1     9
2    -1
3    10
4     7
Name: Name, dtype: int64

In [54]:
##count passenger with 'Miss' in name

df['Name'].str.contains('Miss').sum()

np.int64(182)

In [57]:
data = {
    'Name': [
        'John Doe' , 'Jane Smith', 'Emily Johnson', 
        'Robert Brown', 'Anna-Marie Lee'
    ],

    'eMail': [
        'john@example.com' , 'jane.smith@work.org', 'emily_j@data.net', 
        'robertb@yahoo.com', 'anna.lee@company.co'

    ]}

df = pd.DataFrame(data)

In [58]:
df.head()

             Name                eMail
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [60]:
df['Name'].str.pad(width=20, side='left', fillchar='-')

0    ------------John Doe
1    ----------Jane Smith
2    -------Emily Johnson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: str

**Categorical Data in Pandas**

- Categorical data represents variables that take on a limited, fixed number of possible values (categories).
- Examples: Gender, City, Product Type, Grade (A/B/C), etc.
- In Pandas, categorical data is handled using the category dtype.

In [71]:
class_data = {
'Name' : ['A', 'B', 'C', 'D'],
"Groups": ['G1', 'G2', 'G3', 'G4']

}

In [72]:
class_df = pd.DataFrame(class_data)

In [73]:
class_df.head()

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

G3 , G1, G2, G4 - Ascending Order

In [74]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [85]:
class_df['Groups_cat'] = pd.Categorical(
    class_df['Groups'],
    categories = ['G3', 'G1', 'G2', 'G4'], #custom order in ascending order i.e. lower to higher
    ordered=True
)

In [80]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Groups      4 non-null      str
 2   Groups_cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [81]:
class_df['Groups_cat'].cat.categories

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [84]:
class_df['Groups_cat'] >= 'G4'

0    False
1    False
2    False
3     True
Name: Groups_cat, dtype: bool

In [86]:
df = pd.read_csv(titanic_dataset_github_url)

In [88]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [89]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [ ]:
#embarked = port where the passenger boarded the ship
# C - Chebough
# S - Southamption
# Q - Queenstown

df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [92]:
df['Embarked'] = df['Embarked'].fillna('N')

In [93]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [95]:
# C - Chebough
# S - Southamption
# Q - Queenstown
# N - Not Defined

# Lets define as N, S, C, Q in ascending order

In [97]:
df['Embarked_auto_cat'] = df['Embarked'].astype('category')

In [98]:
df['Embarked_auto_cat'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [101]:
df['Embarked_cust_cat'] = pd.Categorical(
    df['Embarked'],
    categories = ['N', 'S', 'C', 'Q'], #custom order in ascending order
    ordered=True
)

In [102]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [103]:
df['Embarked_cust_cat'] > 'S'

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890     True
Name: Embarked_cust_cat, Length: 891, dtype: bool

In [105]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [107]:
df['Embarked_cust_cat'].cat.codes.head()

0    1
1    2
2    1
3    1
4    1
dtype: int8

Convert the values of Sex column and encode them in 0 & 1

In [111]:
df['sex'] = df['Sex'].astype('category').cat.codes

In [114]:
df['sex'].head()

0    1
1    0
2    0
3    0
4    1
Name: sex, dtype: int8

In [124]:
df['sex'] = df['Sex'].apply(lambda sex: 1 if sex == 'male' else 0)

In [125]:
df['sex'].head()

0    1
1    0
2    0
3    0
4    1
Name: sex, dtype: int64

**Date Functionality in Pandas**
- Working with dates is very common in data analysis. Pandas provides powerful tools through the datetime and dt accessor.

In [127]:
df = pd.DataFrame({
    'Event' : ['Concert', 'Conference', 'Wedding'],
    'Date' : ['2025-01-01', '2025-03-15', '2025-07-20']

})

In [128]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Event   3 non-null      str
 1   Date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [129]:
df

        Event        Date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [165]:
df['date_pandas'] = pd.to_datetime(df['Date'])

In [166]:
df['date_pandas']

0   2025-01-01
1   2025-03-15
2   2025-07-20
Name: date_pandas, dtype: datetime64[us]

In [133]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Event        3 non-null      str
 1   Date         3 non-null      str
 2   date_pandas  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [134]:
df.head()

        Event        Date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [135]:
df['date_pandas'].dt.year

0    2025
1    2025
2    2025
Name: date_pandas, dtype: int32

In [136]:
df['date_pandas'].dt.month

0    1
1    3
2    7
Name: date_pandas, dtype: int32

In [138]:
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [139]:
df['date_pandas'].dt.weekday

0    2
1    5
2    6
Name: date_pandas, dtype: int32

In [140]:
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: date_pandas, dtype: str

In [142]:
df[df['date_pandas'] > '2025-04-01']

     Event        Date date_pandas
2  Wedding  2025-07-20  2025-07-20

In [145]:
df[df['date_pandas'].between('2025-01-01', '2025-06-01')]

        Event        Date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

**Creating Datetime Ranges**

| Code | Description             |
| ---- | ----------------------- |
| `M`  | Month End               |
| `MS` | Month Start             |
| `W`  | Weekly (Sunday default) |
| `B`  | Business Day            |
| `H`  | Hourly                  |
| `T`  | Minute                  |
| `S`  | Second                  |

In [147]:
pd.date_range(start='2026-02-01', end='2026-02-10', freq='D') #D means all the days

DatetimeIndex(['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
               '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
               '2026-02-09', '2026-02-10'],
              dtype='datetime64[us]', freq='D')

In [150]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='ME') #ME means Month End

DatetimeIndex(['2024-01-31', '2024-02-29'], dtype='datetime64[us]', freq='ME')

In [151]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='MS') #ME means Month End

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64[us]', freq='MS')

**Data Aritmatic**

Data arithmetic in Pandas allows mathematical operations between:
- Series
- DataFrames
- Series and DataFrame
- Scalars and Pandas objects

Pandas automatically aligns data based on index labels.

In [167]:
df['next_week'] = df['date_pandas'] + pd.Timedelta(days=7)

In [168]:
pd.Timedelta(days=7)

Timedelta('7 days 00:00:00')

In [169]:
df.head()

        Event        Date date_pandas  next_week
0     Concert  2025-01-01  2025-01-01 2025-01-08
1  Conference  2025-03-15  2025-03-15 2025-03-22
2     Wedding  2025-07-20  2025-07-20 2025-07-27

In [171]:
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [172]:
df.head()

        Event        Date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -425 days +22:24:33.214708
1  Conference  2025-03-15  2025-03-15 2025-03-22 -352 days +22:24:33.214708
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -225 days +22:24:33.214708

In [ ]:
1 + 1